-- MySQL Script generated by MySQL Workbench
-- Sat Mar 13 12:57:41 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Library
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Library
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Library` DEFAULT CHARACTER SET utf8 ;
USE `Library` ;

-- -----------------------------------------------------
-- Table `Library`.`Customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Library`.`Customer` (
  `CustomerID` INT NOT NULL,
  `Customer_Name` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Address` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`CustomerID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Library`.`Inventory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Library`.`Inventory` (
  `Coustomer_ID` INT NOT NULL,
  `Book_ID` INT NOT NULL,
  `Book_Numbers` INT NOT NULL,
  `OrderID` INT NOT NULL,
  `Customer_CustomerID` INT NOT NULL,
  PRIMARY KEY (`OrderID`),
  INDEX `fk_Inventory_Customer1_idx` (`Customer_CustomerID` ASC) VISIBLE,
  CONSTRAINT `fk_Inventory_Customer1`
    FOREIGN KEY (`Customer_CustomerID`)
    REFERENCES `Library`.`Customer` (`CustomerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Library`.`Book`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Library`.`Book` (
  `BookID` INT NOT NULL,
  `Authour_Name` VARCHAR(45) NOT NULL,
  `Book_Title` VARCHAR(45) NOT NULL,
  `ISBN` INT NOT NULL,
  `Inventory_OrderID` INT NOT NULL,
  PRIMARY KEY (`BookID`),
  INDEX `fk_Book_Inventory_idx` (`Inventory_OrderID` ASC) VISIBLE,
  CONSTRAINT `fk_Book_Inventory`
    FOREIGN KEY (`Inventory_OrderID`)
    REFERENCES `Library`.`Inventory` (`OrderID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
